export type SiteRouteFamily =
  | 'main'
  | 'systems'
  | 'outdoor-rooms'
  | 'commercial'
  | 'service-areas'
  | 'local-products'
  | 'guides'
  | 'projects'
  | 'utility';

export type SiteRouteStatus = 'active' | 'hidden';

export type SiteRouteNavGroup =
  | 'products'
  | 'outdoorRooms'
  | 'locations'
  | 'localProducts'
  | 'work'
  | 'guides'
  | 'commercial';

export type SiteRouteFooterGroup =
  | 'systems'
  | 'outdoorRooms'
  | 'commercial'
  | 'guides'
  | 'locations'
  | 'localProducts'
  | 'work'
  | 'utility';

export type SiteRoute = {
  href: string;
  label: string;
  family: SiteRouteFamily;
  xmlSitemap: boolean;
  htmlSitemap: boolean;
  navGroup?: SiteRouteNavGroup;
  footerGroup?: SiteRouteFooterGroup;
  priority: number;
  status: SiteRouteStatus;
  desc?: string;
  region?: string;
};

export const siteRoutes: SiteRoute[] = [
  {
    href: '/',
    label: 'Home',
    family: 'main',
    xmlSitemap: true,
    htmlSitemap: true,
    priority: 1,
    status: 'active',
  },
  {
    href: '/contact',
    label: 'Contact',
    family: 'main',
    xmlSitemap: true,
    htmlSitemap: true,
    footerGroup: 'utility',
    priority: 0.8,
    status: 'active',
  },
  {
    href: '/showroom',
    label: 'Showroom',
    family: 'main',
    xmlSitemap: true,
    htmlSitemap: true,
    navGroup: 'work',
    footerGroup: 'work',
    priority: 0.8,
    status: 'active',
    desc: 'Visit the Spring Grove showroom',
  },
  {
    href: '/trade-partners',
    label: 'Trade Partners',
    family: 'main',
    xmlSitemap: true,
    htmlSitemap: true,
    footerGroup: 'utility',
    priority: 0.8,
    status: 'active',
  },
  {
    href: '/gallery',
    label: 'Gallery',
    family: 'main',
    xmlSitemap: true,
    htmlSitemap: true,
    navGroup: 'work',
    footerGroup: 'work',
    priority: 0.8,
    status: 'active',
    desc: 'Completed spaces and product details',
  },
  {
    href: '/projects',
    label: 'Projects',
    family: 'projects',
    xmlSitemap: true,
    htmlSitemap: true,
    navGroup: 'work',
    footerGroup: 'work',
    priority: 0.8,
    status: 'active',
    desc: 'Portfolio with installed project examples',
  },
  {
    href: '/systems',
    label: 'All Systems',
    family: 'systems',
    xmlSitemap: true,
    htmlSitemap: true,
    footerGroup: 'systems',
    priority: 0.8,
    status: 'active',
  },
  {
    href: '/systems/pergolas',
    label: 'Pergolas',
    family: 'systems',
    xmlSitemap: true,
    htmlSitemap: true,
    navGroup: 'products',
    footerGroup: 'systems',
    priority: 0.9,
    status: 'active',
    desc: 'Motorized louvered roof systems',
  },
  {
    href: '/systems/pergolas/configure',
    label: '3D Pergola Configurator',
    family: 'systems',
    xmlSitemap: true,
    htmlSitemap: true,
    footerGroup: 'systems',
    priority: 0.85,
    status: 'active',
    desc: 'Explore a pergola layout before a fit review',
  },
  {
    href: '/systems/shades',
    label: 'Screens',
    family: 'systems',
    xmlSitemap: true,
    htmlSitemap: true,
    navGroup: 'products',
    footerGroup: 'systems',
    priority: 0.9,
    status: 'active',
    desc: 'Retractable exterior shades',
  },
  {
    href: '/systems/enclosures',
    label: 'Enclosures',
    family: 'systems',
    xmlSitemap: true,
    htmlSitemap: true,
    navGroup: 'products',
    footerGroup: 'systems',
    priority: 0.9,
    status: 'active',
    desc: 'Glass wall systems',
  },
  {
    href: '/systems/appliances',
    label: 'Outdoor Kitchens',
    family: 'systems',
    xmlSitemap: true,
    htmlSitemap: true,
    navGroup: 'products',
    footerGroup: 'systems',
    priority: 0.9,
    status: 'active',
    desc: 'Built-in grills and appliances',
  },
  {
    href: '/systems/saunas',
    label: 'Saunas',
    family: 'systems',
    xmlSitemap: true,
    htmlSitemap: true,
    navGroup: 'products',
    footerGroup: 'systems',
    priority: 0.9,
    status: 'active',
    desc: 'Premium outdoor sauna systems',
  },
  {
    href: '/outdoor-rooms',
    label: 'Outdoor Rooms',
    family: 'outdoor-rooms',
    xmlSitemap: true,
    htmlSitemap: true,
    navGroup: 'outdoorRooms',
    footerGroup: 'outdoorRooms',
    priority: 0.85,
    status: 'active',
    desc: 'Multi-system patio and outdoor room plans',
  },
  {
    href: '/outdoor-rooms/pergola-glass-outdoor-room',
    label: 'Pergola + Glass Outdoor Room',
    family: 'outdoor-rooms',
    xmlSitemap: true,
    htmlSitemap: true,
    navGroup: 'outdoorRooms',
    footerGroup: 'outdoorRooms',
    priority: 0.85,
    status: 'active',
    desc: 'Protected patio concept with louvers and frameless glass',
  },
  {
    href: '/commercial',
    label: 'Commercial',
    family: 'commercial',
    xmlSitemap: true,
    htmlSitemap: true,
    navGroup: 'commercial',
    footerGroup: 'commercial',
    priority: 0.9,
    status: 'active',
    desc: 'Outdoor revenue spaces for hospitality and shared properties',
  },
  {
    href: '/commercial/chicago-hospitality-outdoor-living',
    label: 'Hospitality Outdoor Living',
    family: 'commercial',
    xmlSitemap: true,
    htmlSitemap: true,
    navGroup: 'commercial',
    footerGroup: 'commercial',
    priority: 0.8,
    status: 'active',
    desc: 'Commercial patio planning for Chicago hospitality spaces',
  },
  {
    href: '/commercial/restaurant-patio-enclosures',
    label: 'Restaurant Patio Enclosures',
    family: 'commercial',
    xmlSitemap: true,
    htmlSitemap: true,
    navGroup: 'commercial',
    footerGroup: 'commercial',
    priority: 0.8,
    status: 'active',
    desc: 'Roof, glass, screens, heat and shade for outdoor dining',
  },
  {
    href: '/commercial/restaurant-patio-solutions',
    label: 'Restaurant Patio Solutions',
    family: 'commercial',
    xmlSitemap: true,
    htmlSitemap: true,
    navGroup: 'commercial',
    footerGroup: 'commercial',
    priority: 0.7,
    status: 'active',
    desc: 'Patio comfort planning for food and beverage operators',
  },
  {
    href: '/commercial/hotel-roof-deck-systems',
    label: 'Hotel Roof Deck Systems',
    family: 'commercial',
    xmlSitemap: true,
    htmlSitemap: true,
    navGroup: 'commercial',
    footerGroup: 'commercial',
    priority: 0.8,
    status: 'active',
    desc: 'Pool decks, rooftop bars and guest amenity spaces',
  },
  {
    href: '/commercial/hotel-pergolas',
    label: 'Hotel Pergolas',
    family: 'commercial',
    xmlSitemap: true,
    htmlSitemap: true,
    navGroup: 'commercial',
    footerGroup: 'commercial',
    priority: 0.9,
    status: 'active',
    desc: 'Pergola planning for hotel patios, pools and amenity spaces',
  },
  {
    href: '/commercial/country-club-outdoor-spaces',
    label: 'Country Clubs',
    family: 'commercial',
    xmlSitemap: true,
    htmlSitemap: true,
    navGroup: 'commercial',
    footerGroup: 'commercial',
    priority: 0.8,
    status: 'active',
    desc: 'Dining terraces, pool decks and event-ready outdoor areas',
  },
  {
    href: '/commercial/west-loop',
    label: 'West Loop Projects',
    family: 'commercial',
    xmlSitemap: true,
    htmlSitemap: true,
    navGroup: 'commercial',
    footerGroup: 'commercial',
    priority: 0.7,
    status: 'active',
    desc: 'Chicago hospitality context for dense urban patios',
  },
  {
    href: '/service-areas',
    label: 'All Service Areas',
    family: 'service-areas',
    xmlSitemap: true,
    htmlSitemap: true,
    footerGroup: 'locations',
    priority: 0.8,
    status: 'active',
  },
  {
    href: '/service-areas/chicago-il',
    label: 'Chicago, IL',
    family: 'service-areas',
    xmlSitemap: true,
    htmlSitemap: true,
    navGroup: 'locations',
    footerGroup: 'locations',
    priority: 0.9,
    status: 'active',
    region: 'Chicago',
    desc: 'Urban roof decks, masonry patios, and tight-lot outdoor living tailored to Chicago neighborhoods.',
  },
  {
    href: '/service-areas/spring-grove-il',
    label: 'Spring Grove, IL',
    family: 'service-areas',
    xmlSitemap: true,
    htmlSitemap: true,
    navGroup: 'locations',
    footerGroup: 'locations',
    priority: 0.9,
    status: 'active',
    region: 'Showroom',
    desc: 'Our home base and showroom. See motorized pergolas, patio screens, and outdoor living systems before you build.',
  },
  {
    href: '/service-areas/algonquin-il',
    label: 'Algonquin, IL',
    family: 'service-areas',
    xmlSitemap: true,
    htmlSitemap: true,
    priority: 0.9,
    status: 'active',
    region: 'McHenry County',
    desc: 'Fox River Valley pergola planning for Old Town, Randall Road neighborhoods, permits, screens, and flexible patio comfort.',
  },
  {
    href: '/service-areas/lake-county-il',
    label: 'Lake County, IL',
    family: 'service-areas',
    xmlSitemap: true,
    htmlSitemap: true,
    priority: 0.8,
    status: 'active',
    region: 'North Shore',
    desc: 'Lake County outdoor living planning for premium patios, decks, and estate properties.',
  },
  {
    href: '/service-areas/mchenry-county-il',
    label: 'McHenry County, IL',
    family: 'service-areas',
    xmlSitemap: true,
    htmlSitemap: true,
    priority: 0.8,
    status: 'active',
    region: 'McHenry County',
    desc: 'Northwest suburban pergola, shade, and screen planning for larger lots and rural edges.',
  },
  {
    href: '/service-areas/north-shore-chicago',
    label: 'North Shore Chicago',
    family: 'service-areas',
    xmlSitemap: true,
    htmlSitemap: true,
    navGroup: 'locations',
    footerGroup: 'locations',
    priority: 0.8,
    status: 'active',
    region: 'North Shore',
    desc: 'Lakefront homes and estate properties',
  },
  {
    href: '/service-areas/southeast-wisconsin',
    label: 'Southeast Wisconsin',
    family: 'service-areas',
    xmlSitemap: true,
    htmlSitemap: true,
    priority: 0.8,
    status: 'active',
    region: 'Wisconsin',
    desc: 'Southeast Wisconsin outdoor living planning near the Chicago-Milwaukee corridor.',
  },
  {
    href: '/service-areas/milwaukee-wi',
    label: 'Milwaukee, WI',
    family: 'service-areas',
    xmlSitemap: true,
    htmlSitemap: true,
    navGroup: 'locations',
    footerGroup: 'locations',
    priority: 0.9,
    status: 'active',
    region: 'Wisconsin',
    desc: 'Motorized pergola, screen, and permit-aware outdoor-room planning for Milwaukee patios, yards, and urban outdoor spaces.',
  },
  {
    href: '/service-areas/naperville-il',
    label: 'Naperville, IL',
    family: 'service-areas',
    xmlSitemap: true,
    htmlSitemap: true,
    navGroup: 'locations',
    footerGroup: 'locations',
    priority: 0.8,
    status: 'active',
    region: 'West Suburbs',
    desc: 'Historic downtown to new developments. HOA-compliant designs for western suburbs.',
  },
  {
    href: '/service-areas/barrington-il',
    label: 'Barrington, IL',
    family: 'service-areas',
    xmlSitemap: true,
    htmlSitemap: true,
    navGroup: 'locations',
    footerGroup: 'locations',
    priority: 0.8,
    status: 'active',
    region: 'Northwest Suburbs',
    desc: 'Estate properties and equestrian communities. Large-span engineering for expansive patios.',
  },
  {
    href: '/service-areas/oak-brook-il',
    label: 'Oak Brook, IL',
    family: 'service-areas',
    xmlSitemap: true,
    htmlSitemap: true,
    priority: 0.8,
    status: 'active',
    region: 'West Suburbs',
    desc: 'Estate-style outdoor living for Oak Brook, Burr Ridge, and surrounding western suburbs.',
  },
  {
    href: '/service-areas/lake-geneva-wi',
    label: 'Lake Geneva, WI',
    family: 'service-areas',
    xmlSitemap: true,
    htmlSitemap: true,
    navGroup: 'locations',
    footerGroup: 'locations',
    priority: 0.8,
    status: 'active',
    region: 'Wisconsin',
    desc: 'Lakefront pergolas, motorized screens, permit planning, and outdoor-room design for Geneva Lake area homes.',
  },
  {
    href: '/service-areas/hinsdale-il',
    label: 'Hinsdale, IL',
    family: 'service-areas',
    xmlSitemap: true,
    htmlSitemap: true,
    priority: 0.8,
    status: 'active',
    region: 'West Suburbs',
    desc: 'Premier estates and historic properties. Custom designs for The Lane and surrounding areas.',
  },
  {
    href: '/service-areas/southwest-florida',
    label: 'Southwest Florida',
    family: 'service-areas',
    xmlSitemap: true,
    htmlSitemap: true,
    navGroup: 'locations',
    footerGroup: 'locations',
    priority: 0.9,
    status: 'active',
    region: 'Florida',
    desc: 'Gulf Coast screens and pergolas',
  },
  {
    href: '/service-areas/sanibel-outdoor-living',
    label: 'Sanibel, FL',
    family: 'service-areas',
    xmlSitemap: true,
    htmlSitemap: true,
    navGroup: 'locations',
    footerGroup: 'locations',
    priority: 0.8,
    status: 'active',
    region: 'Florida',
    desc: 'Gulf Coast outdoor living',
  },
  {
    href: '/service-areas/northbrook-il',
    label: 'Northbrook, IL',
    family: 'service-areas',
    xmlSitemap: true,
    htmlSitemap: true,
    priority: 0.8,
    status: 'active',
    region: 'North Shore',
    desc: 'From Techny to Northbrook Heights. Outdoor living systems for Cook County homes.',
  },
  {
    href: '/service-areas/deerfield-il',
    label: 'Deerfield, IL',
    family: 'service-areas',
    xmlSitemap: true,
    htmlSitemap: true,
    priority: 0.8,
    status: 'active',
    region: 'North Shore',
    desc: 'Motorized patio screens and outdoor living systems for North Shore homes that need privacy, bug control, and wind protection.',
  },
  {
    href: '/service-areas/lake-forest-il',
    label: 'Lake Forest, IL',
    family: 'service-areas',
    xmlSitemap: true,
    htmlSitemap: true,
    navGroup: 'locations',
    footerGroup: 'locations',
    priority: 0.9,
    status: 'active',
    region: 'North Shore',
    desc: 'Permit-aware motorized pergola and outdoor room planning for lakefront homes, wooded lots, and west-side estates.',
  },
  {
    href: '/service-areas/wilmette-il',
    label: 'Wilmette, IL',
    family: 'service-areas',
    xmlSitemap: true,
    htmlSitemap: true,
    priority: 0.8,
    status: 'active',
    region: 'North Shore',
    desc: 'Historic districts to lakefront estates. Zoning-compliant outdoor living for North Shore homes.',
  },
  {
    href: '/service-areas/winnetka-il',
    label: 'Winnetka, IL',
    family: 'service-areas',
    xmlSitemap: true,
    htmlSitemap: true,
    priority: 0.8,
    status: 'active',
    region: 'North Shore',
    desc: 'Estate-scale installations with architectural review board expertise for prestigious properties.',
  },
  {
    href: '/service-areas/southwest-florida/motorized-screens',
    label: 'Southwest Florida Motorized Screens',
    family: 'local-products',
    xmlSitemap: true,
    htmlSitemap: true,
    navGroup: 'localProducts',
    footerGroup: 'localProducts',
    priority: 0.9,
    status: 'active',
    desc: 'Motorized lanai and patio screen planning for Gulf Coast homes.',
  },
  {
    href: '/service-areas/sanibel-outdoor-living/louvered-pergolas',
    label: 'Sanibel Louvered Pergolas',
    family: 'local-products',
    xmlSitemap: true,
    htmlSitemap: true,
    navGroup: 'localProducts',
    footerGroup: 'localProducts',
    priority: 0.8,
    status: 'active',
    desc: 'Coastal pergola guidance for Sanibel and Captiva homes.',
  },
  {
    href: '/service-areas/sanibel-outdoor-living/modern-lanai',
    label: 'Modern Lanai Sanibel',
    family: 'local-products',
    xmlSitemap: true,
    htmlSitemap: true,
    footerGroup: 'localProducts',
    priority: 0.8,
    status: 'active',
    desc: 'Related outdoor-room path for modernizing a Sanibel lanai.',
  },
  {
    href: '/service-areas/sanibel-outdoor-living/lanai-replacement',
    label: 'Sanibel Lanai Replacement',
    family: 'local-products',
    xmlSitemap: true,
    htmlSitemap: true,
    footerGroup: 'localProducts',
    priority: 0.8,
    status: 'active',
    desc: 'Rebuild damaged lanais with modern systems designed for coastal code pressure.',
  },
  {
    href: '/service-areas/sanibel-outdoor-living/zoning-guide',
    label: 'Sanibel Permit Guide',
    family: 'local-products',
    xmlSitemap: true,
    htmlSitemap: true,
    navGroup: 'localProducts',
    footerGroup: 'localProducts',
    priority: 0.8,
    status: 'active',
    desc: 'Permit, floodplain, product approval, and 50% rule guidance for Sanibel outdoor living projects.',
  },
  {
    href: '/service-areas/barrington-il/motorized-pergolas',
    label: 'Barrington Motorized Pergolas',
    family: 'local-products',
    xmlSitemap: true,
    htmlSitemap: true,
    footerGroup: 'localProducts',
    priority: 0.8,
    status: 'active',
    desc: 'Large-span motorized pergola planning for Barrington estates and patios.',
  },
  {
    href: '/service-areas/algonquin-il/motorized-pergolas',
    label: 'Algonquin Motorized Pergolas',
    family: 'local-products',
    xmlSitemap: true,
    htmlSitemap: true,
    navGroup: 'localProducts',
    footerGroup: 'localProducts',
    priority: 0.9,
    status: 'active',
    desc: 'Fox River Valley pergola planning for shade, rain, bugs, privacy, and permits.',
  },
  {
    href: '/service-areas/algonquin-il/retractable-screens',
    label: 'Algonquin Motorized Screens',
    family: 'local-products',
    xmlSitemap: true,
    htmlSitemap: true,
    footerGroup: 'localProducts',
    priority: 0.9,
    status: 'active',
    desc: 'Retractable patio screen layouts for bugs, glare, privacy, wind, and pergola openings.',
  },
  {
    href: '/service-areas/algonquin-il/zoning-guide',
    label: 'Algonquin Pergola Permit Guide',
    family: 'local-products',
    xmlSitemap: true,
    htmlSitemap: true,
    footerGroup: 'localProducts',
    priority: 0.8,
    status: 'active',
    desc: 'Permit and zoning notes for Algonquin pergola planning.',
  },
  {
    href: '/service-areas/chicago-il/motorized-pergolas',
    label: 'Chicago Motorized Pergolas',
    family: 'local-products',
    xmlSitemap: true,
    htmlSitemap: true,
    navGroup: 'localProducts',
    footerGroup: 'localProducts',
    priority: 0.9,
    status: 'active',
    desc: 'Pergola planning for Chicago rooftops, tight lots, masonry patios, and permit-aware outdoor rooms.',
  },
  {
    href: '/service-areas/chicago-il/retractable-screens',
    label: 'Chicago Retractable Screens',
    family: 'local-products',
    xmlSitemap: true,
    htmlSitemap: true,
    navGroup: 'localProducts',
    footerGroup: 'localProducts',
    priority: 0.9,
    status: 'active',
    desc: 'Outdoor screen planning for city patios, roof decks, and covered spaces.',
  },
  {
    href: '/service-areas/chicago-il/glass-enclosures',
    label: 'Chicago Glass Enclosures',
    family: 'local-products',
    xmlSitemap: true,
    htmlSitemap: true,
    navGroup: 'localProducts',
    footerGroup: 'localProducts',
    priority: 0.9,
    status: 'active',
    desc: 'Frameless glass walls for wind, rain, views, and flexible patio use.',
  },
  {
    href: '/service-areas/deerfield-il/retractable-screens',
    label: 'Deerfield Retractable Screens',
    family: 'local-products',
    xmlSitemap: true,
    htmlSitemap: true,
    footerGroup: 'localProducts',
    priority: 0.9,
    status: 'active',
    desc: 'North Shore screen layouts for bugs, privacy, sun, and wind control.',
  },
  {
    href: '/service-areas/lake-forest-il/motorized-pergolas',
    label: 'Lake Forest Motorized Pergolas',
    family: 'local-products',
    xmlSitemap: true,
    htmlSitemap: true,
    footerGroup: 'localProducts',
    priority: 0.9,
    status: 'active',
    desc: 'Permit-aware pergola planning for lakefront homes, wooded yards, and estate patios.',
  },
  {
    href: '/service-areas/lake-forest-il/zoning-guide',
    label: 'Lake Forest Pergola Permit Guide',
    family: 'local-products',
    xmlSitemap: true,
    htmlSitemap: true,
    footerGroup: 'localProducts',
    priority: 0.8,
    status: 'active',
    desc: 'Building permit, accessory-structure, and plan-review notes for Lake Forest outdoor living projects.',
  },
  {
    href: '/service-areas/lake-geneva-wi/motorized-pergolas',
    label: 'Lake Geneva Motorized Pergolas',
    family: 'local-products',
    xmlSitemap: true,
    htmlSitemap: true,
    navGroup: 'localProducts',
    footerGroup: 'localProducts',
    priority: 0.9,
    status: 'active',
    desc: 'Louvered roof planning for lake wind, views, shade, rain control, screens, and outdoor entertaining.',
  },
  {
    href: '/service-areas/lake-geneva-wi/retractable-screens',
    label: 'Lake Geneva Motorized Screens',
    family: 'local-products',
    xmlSitemap: true,
    htmlSitemap: true,
    navGroup: 'localProducts',
    footerGroup: 'localProducts',
    priority: 0.9,
    status: 'active',
    desc: 'Retractable screen layouts for bugs, glare, privacy, wind comfort, and flexible screen-room use.',
  },
  {
    href: '/service-areas/lake-geneva-wi/zoning-guide',
    label: 'Lake Geneva Pergola Permit Guide',
    family: 'local-products',
    xmlSitemap: true,
    htmlSitemap: true,
    footerGroup: 'localProducts',
    priority: 0.8,
    status: 'active',
    desc: 'Permit and review planning notes for Lake Geneva, Fontana, Williams Bay, and Walworth County projects.',
  },
  {
    href: '/service-areas/milwaukee-wi/motorized-pergolas',
    label: 'Milwaukee Motorized Pergolas',
    family: 'local-products',
    xmlSitemap: true,
    htmlSitemap: true,
    navGroup: 'localProducts',
    footerGroup: 'localProducts',
    priority: 0.9,
    status: 'active',
    desc: 'Louvered roof planning for Milwaukee patios, urban outdoor spaces, screens, lighting, rain control, and permit questions.',
  },
  {
    href: '/service-areas/milwaukee-wi/zoning-guide',
    label: 'Milwaukee Pergola Permit Guide',
    family: 'local-products',
    xmlSitemap: true,
    htmlSitemap: true,
    navGroup: 'localProducts',
    footerGroup: 'localProducts',
    priority: 0.8,
    status: 'active',
    desc: 'Official City resources and cautious permit-planning guidance for Milwaukee pergola and outdoor-room projects.',
  },
  {
    href: '/service-areas/northbrook-il/motorized-pergolas',
    label: 'Northbrook Motorized Pergolas',
    family: 'local-products',
    xmlSitemap: true,
    htmlSitemap: true,
    footerGroup: 'localProducts',
    priority: 0.8,
    status: 'active',
    desc: 'Motorized pergola planning for Northbrook patios, decks, and Cook County approvals.',
  },
  {
    href: '/service-areas/naperville-il/motorized-pergolas',
    label: 'Naperville Motorized Pergolas',
    family: 'local-products',
    xmlSitemap: true,
    htmlSitemap: true,
    footerGroup: 'localProducts',
    priority: 0.8,
    status: 'active',
    desc: 'HOA-aware motorized pergola planning for Naperville homes and patios.',
  },
  {
    href: '/service-areas/wilmette-il/louvered-pergolas',
    label: 'Wilmette Louvered Pergolas',
    family: 'local-products',
    xmlSitemap: true,
    htmlSitemap: true,
    footerGroup: 'localProducts',
    priority: 0.8,
    status: 'active',
    desc: 'North Shore louvered pergola guidance for Wilmette homes.',
  },
  {
    href: '/service-areas/winnetka-il/louvered-pergolas',
    label: 'Winnetka Louvered Pergolas',
    family: 'local-products',
    xmlSitemap: true,
    htmlSitemap: true,
    footerGroup: 'localProducts',
    priority: 0.8,
    status: 'active',
    desc: 'Estate-scale louvered pergola guidance for Winnetka homes.',
  },
  {
    href: '/guides',
    label: 'Guides',
    family: 'guides',
    xmlSitemap: true,
    htmlSitemap: true,
    footerGroup: 'guides',
    priority: 0.8,
    status: 'active',
  },
  {
    href: '/guides/planning-guide',
    label: 'Planning Guide',
    family: 'guides',
    xmlSitemap: true,
    htmlSitemap: true,
    footerGroup: 'guides',
    priority: 0.8,
    status: 'active',
    desc: 'Start with goals, constraints, and planning basics',
  },
  {
    href: '/guides/planning-guide/read',
    label: 'Planning Guide Reader',
    family: 'guides',
    xmlSitemap: false,
    htmlSitemap: false,
    priority: 0,
    status: 'hidden',
  },
  {
    href: '/guides/motorized-pergola-planning',
    label: 'Pergola Planning Guide',
    family: 'guides',
    xmlSitemap: true,
    htmlSitemap: true,
    navGroup: 'guides',
    footerGroup: 'guides',
    priority: 0.9,
    status: 'active',
    desc: 'Cost, fit, drainage, controls, accessories and constraints',
  },
  {
    href: '/guides/louvered-pergolas',
    label: 'Louvered Pergolas Guide',
    family: 'guides',
    xmlSitemap: true,
    htmlSitemap: true,
    footerGroup: 'guides',
    priority: 0.9,
    status: 'active',
    desc: 'Plain-English guide to choosing louvered pergolas',
  },
  {
    href: '/guides/pergola-system-fit-review',
    label: 'System Fit Review',
    family: 'guides',
    xmlSitemap: true,
    htmlSitemap: true,
    navGroup: 'guides',
    footerGroup: 'guides',
    priority: 0.9,
    status: 'active',
    desc: 'Share photos and goals so EDG can identify the likely path',
  },
  {
    href: '/guides/motorized-pergola-budget-examples',
    label: 'Budget Examples',
    family: 'guides',
    xmlSitemap: true,
    htmlSitemap: true,
    navGroup: 'guides',
    footerGroup: 'guides',
    priority: 0.85,
    status: 'active',
    desc: 'Realistic planning bands for premium outdoor living projects',
  },
  {
    href: '/guides/motorized-pergola-deck-roof-deck',
    label: 'Deck and Roof Deck Pergolas',
    family: 'guides',
    xmlSitemap: true,
    htmlSitemap: true,
    footerGroup: 'guides',
    priority: 0.85,
    status: 'active',
    desc: 'Planning notes for decks, roof decks, attachment, and structure',
  },
  {
    href: '/guides/motorized-pergola-permits-hoa-engineering',
    label: 'Permits, HOA and Engineering',
    family: 'guides',
    xmlSitemap: true,
    htmlSitemap: true,
    navGroup: 'guides',
    footerGroup: 'guides',
    priority: 0.85,
    status: 'active',
    desc: 'How approvals, drawings and site details shape the project',
  },
  {
    href: '/guides/pergola-cost',
    label: 'Pergola Cost Guide',
    family: 'guides',
    xmlSitemap: true,
    htmlSitemap: true,
    navGroup: 'guides',
    footerGroup: 'guides',
    priority: 0.9,
    status: 'active',
    desc: 'What drives premium pergola pricing and project scope',
  },
  {
    href: '/guides/louvered-pergola-brands-compared',
    label: 'Pergola System Comparison',
    family: 'guides',
    xmlSitemap: true,
    htmlSitemap: true,
    navGroup: 'guides',
    footerGroup: 'guides',
    priority: 0.8,
    status: 'active',
    desc: 'How EDG matches brand, site, budget and feature needs',
  },
  {
    href: '/guides/pergola-vs-patio-cover',
    label: 'Pergola vs Patio Cover',
    family: 'guides',
    xmlSitemap: true,
    htmlSitemap: true,
    footerGroup: 'guides',
    priority: 0.8,
    status: 'active',
    desc: 'Compare shade structures and covered patio paths',
  },
  {
    href: '/guides/magnatrack-screens-cost',
    label: 'MagnaTrack Screens Cost',
    family: 'guides',
    xmlSitemap: true,
    htmlSitemap: true,
    navGroup: 'guides',
    footerGroup: 'guides',
    priority: 0.9,
    status: 'active',
    desc: 'Budget factors for motorized screens and shade retrofits',
  },
  {
    href: '/privacy',
    label: 'Privacy Policy',
    family: 'utility',
    xmlSitemap: true,
    htmlSitemap: true,
    footerGroup: 'utility',
    priority: 0.5,
    status: 'active',
  },
  {
    href: '/terms',
    label: 'Terms of Service',
    family: 'utility',
    xmlSitemap: true,
    htmlSitemap: true,
    footerGroup: 'utility',
    priority: 0.5,
    status: 'active',
  },
  {
    href: '/html-sitemap',
    label: 'HTML Sitemap',
    family: 'utility',
    xmlSitemap: true,
    htmlSitemap: false,
    footerGroup: 'utility',
    priority: 0.5,
    status: 'active',
  },
];

export const routeFamilies = [
  'main',
  'systems',
  'outdoor-rooms',
  'commercial',
  'service-areas',
  'local-products',
  'guides',
  'projects',
  'utility',
] as const satisfies readonly SiteRouteFamily[];

export function getRoutesByNavGroup(group: SiteRouteNavGroup) {
  return siteRoutes.filter(
    (route) => route.status === 'active' && route.navGroup === group
  );
}

export function getRoutesByFooterGroup(group: SiteRouteFooterGroup) {
  return siteRoutes.filter(
    (route) => route.status === 'active' && route.footerGroup === group
  );
}

export function getRoutesByFamily(family: SiteRouteFamily) {
  return siteRoutes.filter(
    (route) => route.status === 'active' && route.family === family
  );
}

export function getHtmlSitemapRoutes(family: SiteRouteFamily) {
  return siteRoutes.filter(
    (route) =>
      route.status === 'active' && route.family === family && route.htmlSitemap
  );
}

export const xmlSitemapRoutes = siteRoutes.filter(
  (route) => route.status === 'active' && route.xmlSitemap
);

export const productsNavLinks = getRoutesByNavGroup('products');
export const outdoorRoomNavLinks = getRoutesByNavGroup('outdoorRooms');
export const commercialNavLinks = getRoutesByNavGroup('commercial');
export const locationNavLinks = getRoutesByNavGroup('locations');
export const localProductNavLinks = getRoutesByNavGroup('localProducts');
export const guideNavLinks = getRoutesByNavGroup('guides');
export const workNavLinks = getRoutesByNavGroup('work');

export const serviceAreaHubRoutes = getRoutesByFamily('service-areas');
export const priorityLocalProductRoutes = getRoutesByFamily('local-products');
